### ISSUE TITLE
生成合图时遇到异常情况没有抛出实际的错误，导致无法排查问题

### ISSUE THREAD

**Issue by sy-tang** [gkajs/gka#25]
举个例子，当 png 图片的签名非法时，合图出错，但没有抛出实际的错误，继续执行 writeFileSync 的逻辑，最终抛出了 TypeError: Cannot read property 'image' of undefined 的异常，无法获悉具体的错误情况

目前的报错：
```bash
            fs.writeFileSync(filepath, r.image);
                                         ^
TypeError: Cannot read property 'image' of undefined
    at /Users/neal/Workspace/xxx/node_modules/_gka@2.8.4@gka/lib/plugins/ImageSpritesPlugin.js:24:42
    at /Users/neal/Workspace/xxx/node_modules/_mkdirp@0.5.1@mkdirp/index.js:30:20
    at FSReqCallback.oncomplete (fs.js:148:20)
```

实际的错误为：
```bash
Error: Invalid file signature
    at module.exports.Parser._parseSignature (/Users/neal/Workspace/xxx/node_modules/_pngjs@3.3.3@pngjs/lib/parser.js:50:18)
    ...
```

一种解决方案：
```js
// 在合图异常时，直接抛出 error
// ImageSpritePlugin.js:23
function gsprites(srcs, filepath, algorithm, callback) {
    Spritesmith.run({
        src: srcs,
        algorithm: algorithm,
        algorithmOpts: {sort: false},
    }, function(err, r) {
        if (err) throw err;
        mkdirp(path.dirname(filepath), function (err) {
            fs.writeFileSync(filepath, r.image);
            // console.log('[-] ' + path.basename(filepath) +' generated');
            callback && callback(r, filepath);
        });
    });
}
```

**Comment by joeyguo** [comment]
已merge
